name: CMake Build

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging" ]

env:
  BUILD_TYPE: Release
  QT_VERSION: 6.5.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Install Qt (Windows)
      if: matrix.os == 'windows-2019'
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.QT_VERSION }}
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        dir: '${{ github.workspace }}/Qt/'
        install-deps: 'true'
        modules: ''
        archives: 'qtbase'
        cache: 'false'
        cache-key-prefix: 'install-qt-action'
        setup-python: 'true'
        set-env: 'true'
        tools-only: 'false'
        aqtversion: '==2.1.*'
        py7zrversion: '==0.19.*'
        extra: '--external 7z'
    - name: Install Qt (macOs)
      if: matrix.os == 'macos-latest'
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.QT_VERSION }}
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'
        dir: '${{ github.workspace }}/Qt/'
        install-deps: 'true'
        archives: 'qtbase'
        cache: 'false'
        cache-key-prefix: 'install-qt-action'
        setup-python: 'true'
        set-env: 'true'
        tools-only: 'false'
        aqtversion: '==2.1.*'
        py7zrversion: '==0.19.*'
        extra: '--external 7z'
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH=${{github.workspace}}/Qt/${{ env.QT_VERSION }}/${{ matrix.os }}/bin
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
