name: C++ CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            vcpkg_triplet: x64-linux
          - os: windows-latest
            vcpkg_triplet: x64-windows
          - os: macOS-latest
            vcpkg_triplet: x64-osx

    steps:
    - uses: actions/checkout@v2
    - name: Installing CMake
      uses: lukka/get-cmake@v3.26.3
    - name: Setup vcpkg (it does not install any package yet)
      uses: lukka/run-vcpkg@v11
    - name: Run CMake consuming CMakePreset.json and run vcpkg to build dependencies
      uses: lukka/run-cmake@v10
      with:
          configurePreset: 'ninja-multi-vcpkg'
          buildPreset: 'ninja-multi-vcpkg'
    - name: Install packages
      run: vcpkg install --triplet ${{ matrix.triplet }} --recurse --clean-after-build
      env:
        VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
