name: C++ CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            vcpkg_triplet: x64-linux
            vcpkgCommitId: '6a3dd0874f153f8b375ec26210ea6d41dee3bb26'
          - os: windows-latest
            vcpkg_triplet: x64-windows
            vcpkgCommitId: '6a3dd0874f153f8b375ec26210ea6d41dee3bb26'
          - os: macOS-latest
            vcpkg_triplet: x64-osx
            vcpkgCommitId: '6a3dd0874f153f8b375ec26210ea6d41dee3bb26'

    steps:
    - uses: actions/checkout@v2
    - name: Installing CMake
      uses: lukka/get-cmake@v3.26.3
    - name: Setup vcpkg (it does not install any package yet)
      uses: lukka/run-vcpkg@v11
      with:
          vcpkgGitCommitId: '${{ matrix.vcpkgCommitId }}'
          vcpkgJsonGlob: '**/vcpkg.json'
    - name: Run CMake
      uses: lukka/run-cmake@v10
      with:
          configurePreset: 'release'
          buildPreset: 'release'
    - name: Install packages
      run: vcpkg install --triplet ${{ matrix.triplet }} --recurse --clean-after-build
      env:
        VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
