name: C++ CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            vcpkg_triplet: x64-linux
          - os: windows-latest
            vcpkg_triplet: x64-windows
          - os: macOS-latest
            vcpkg_triplet: x64-osx

    steps:
    - uses: actions/checkout@v2
    - uses: lukka/install-vcpkg-deps@v1
    - uses: lukka/get-cmake@v1
    - name: Setup vcpkg
      uses: lukka/setup-vcpkg@v1
    - name: Install packages
      run: vcpkg install --triplet ${{ matrix.triplet }} --recurse --clean-after-build
      env:
        VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
