name: C++ CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            triplet: x64-linux
            vcpkgCommitId: '6a3dd0874f153f8b375ec26210ea6d41dee3bb26'
          - os: windows-latest
            vcpkgCommitId: '6a3dd0874f153f8b375ec26210ea6d41dee3bb26'
            triplet: x64-windows
          - os: macOS-latest
            vcpkgCommitId: '6a3dd0874f153f8b375ec26210ea6d41dee3bb26'
            triplet: x64-osx

    steps:
    - uses: actions/checkout@v3
    - name: Installing CMake
      uses: lukka/get-cmake@v3.26.3
    - name: Download dependencies
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
         sudo apt-get update && sudo apt-get install -y linux-libc-dev build-essential libgl1-mesa-dev autoconf-archive libarchive-dev libfontconfig1-dev libfreetype6-dev libx11-dev libx11-xcb-dev libxext-dev libxfixes-dev libxi-dev libxrender-dev libxcb1-dev libxcb-cursor-dev libxcb-glx0-dev libxcb-keysyms1-dev libxcb-image0-dev libxcb-shm0-dev libxcb-icccm4-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-randr0-dev libxcb-render-util0-dev libxcb-util-dev libxcb-xinerama0-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev
        elif [ "$RUNNER_OS" == "macOS" ]; then
         brew install nasm bison flex gperf node
        elif [ "$RUNNER_OS" == "Windows" ]; then
          echo "Nothing to do."
        fi
      shell: bash
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@main
      with:
          runVcpkgInstall: true
          vcpkgGitCommitId: '${{ matrix.vcpkgCommitId }}'
          vcpkgJsonGlob: '**/vcpkg.json'
    - name: Prints output of run-vcpkg's action
      run: echo "root='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}', triplet='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_DEFAULT_TRIPLET_OUT }}'"
    - name: Run CMake
      uses: lukka/run-cmake@v10
      with:
          configurePreset: 'release'
          buildPreset: 'release'
