name: C++ CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            vcpkg_triplet: x64-linux
          - os: windows-latest
            vcpkg_triplet: x64-windows
          - os: macOS-latest
            vcpkg_triplet: x64-osx

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh

    - name: Install dependencies
      run: |
        vcpkg install --feature-flags=manifests

    - name: Build C++ program
      run: |
        cmake -Bbuild -S. -DCMAKE_TOOLCHAIN_FILE=$(pwd)/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=${{ matrix.vcpkg_triplet }}
        cmake --build build
